apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: go-app
  ports:
  - protocol: TCP
    port: 80         # Port on which the service will be accessible
    targetPort: 8080 # The container port where the app is running
  type: LoadBalancer
